title: xksJsonTextEvent プラグイン
description: RPGツクールMZ用のイベント管理プラグイン「xksJsonTextEvent」を配布しています。
theme: minima
minima:
  skin: classic
  social_links:
    - { platform: github, user_url: "https://github.com/xkslab/vscode-jte-extension" }
    - { platform: twitter, user_url: "https://x.com/xks1620684" }
header_pages:
  - CHANGELOG.md
  - about.md
permalink: /:path/
